---
# The Skylight ID for the application.
application: jpn3MJ7lxS6L

# The authentication token for the application.
authentication: 0rpQMeYGfK+sWsqtnzoqpebla8kDtW8ApmaC1C1D2l9hcHBsaWNhdGlvbl9pZHM9anBuM01KN2x4UzZMJnJvbGU9YWdlbnQ=
